### ISSUE TITLE
Panic in unterminated string

### ISSUE THREAD

**Issue by yhara** [shiika-lang/shiika#189]
```
                    // TODO: should be a LexError
                    panic!("found unterminated string");
```
Lexer should return `Result` rather than using `panic!`.

**Comment by yamakoud** [comment]
It looks like this might have been resolved.

What do you think?

👇 This is my search result on VSCode
<img width="543" alt="image" src="https://github.com/shiika-lang/shiika/assets/86505801/87794f15-fbe2-4795-99ee-b81204a065dd">

**Comment by yhara** [comment]
Oh that's right, thanks!
