### ISSUE TITLE
Impl. Void#to_s

### ISSUE THREAD

**Issue by yhara** [shiika-lang/shiika#248]
So that you can do `p Void`.

But note that `Void` cannot be defined in ./builtin because ::Void holds the instance, not the class.

**Comment by aisk** [comment]
I think this can be defined in `corelib/void.rs`, but I found that there is not a function to build a string in rust.

There is a `gen_string_literal` function, but it only receive usize as it's parameter.

**Comment by yhara** [comment]
> Void cannot be defined in ./builtin
Oh I think this is false now.
