### ISSUE TITLE
Improve error message of return type mismatch

### ISSUE THREAD

**Issue by yhara** [shiika-lang/shiika#381]
## Given

```sk
class A
  def to_s   # Forgot  `-> String`
    "??"
  end
end
puts A.new.to_s
```

## Actual

> Error: the argument `str' of `Object#puts' should be String but got Void

## Expected

Something like "Error: A#to_s must be return String"

**Comment by yamakoud** [comment]
Do you mean to force any to_s function to return a string by default?

**Comment by yhara** [comment]
Yes.

- `to_s` is defined in the `Object` class (`def to_s -> String`)
- Every class is a subclass of `Object`
- So every `to_s` should return String.

**Comment by yamakoud** [comment]
I got it.

Is this dupe of https://github.com/shiika-lang/shiika/issues/361 ?

**Comment by yhara** [comment]
Ohh that's right! 😂
