### ISSUE TITLE
Mac M1 problem

### ISSUE THREAD

**Issue by AI-Mozi** [shiika-lang/shiika#430]
Hi @yhara!
I tried to run shiika locally but encountered this error.
You may have come across something like this ?

```
error: linking with `cc` failed: exit status: 1
...
note: ld: warning: ignoring file /usr/local/Cellar/llvm@12/12.0.1_1/lib/libc++.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
          ld: in '/usr/local/Cellar/llvm@12/12.0.1_1/lib/libunwind.dylib', building for macOS-arm64 but attempting to link with file built for macOS-x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I use mac with M1
Thanks in advance

**Comment by yhara** [comment]
Oh maybe you have two installations of homebrew? Homebrew uses `/opt/homebrew/` on Apple Silicon [since 3.0.0](https://brew.sh/2021/02/05/homebrew-3.0.0/) but I heard that it still uses `/usr/local` when Rosetta 2 is enabled.

**Comment by yhara** [comment]
🎉
