### ISSUE TITLE
Should raise error for extranous arg

### ISSUE THREAD

**Issue by yhara** [shiika-lang/shiika#519]
This should be error but no error raised
```
class A
  def self.run
  end
end
A.run(1)
```

**Comment by yamakoud** [comment]
Can I work on this?

**Comment by yhara** [comment]
@yamakoud yes, please! The first step would be adding a .sk under `tests/erroneous/method_call`. https://github.com/shiika-lang/shiika/tree/main/tests

**Comment by yamakoud** [comment]
I'll submit a pull request later.
